name: Run CI pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      - dev
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review

jobs:
  build:
    if: ${{ !github.event.pull_request.draft }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.2.13

      - name: Install dependencies
        run: bun install

      - name: Check Prettier formatting
        run: bun check-format

      - name: Check ESLint standards
        run: bun check-lint

      - name: Check TypeScript types
        run: bun check-types

      - name: Build app
        run: bun run build
